/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.reservation.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sijo
 */
public class AddAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddAdmin() {
        initComponents();
    }
    private static final String URL = "jdbc:h2:~/BR";
    private static final String USER = "root";
    private static final String PASS = "";

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    ResultSetMetaData rsmd = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PFLpassword = new javax.swing.JPasswordField();
        LUsername = new javax.swing.JLabel();
        LPassword = new javax.swing.JLabel();
        TFLusername = new javax.swing.JTextField();
        BAdd = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        LHeadingLogin = new javax.swing.JLabel();
        LPassword1 = new javax.swing.JLabel();
        TFLname = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        PFLpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PFLpasswordKeyPressed(evt);
            }
        });

        LUsername.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LUsername.setText("Username");

        LPassword.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LPassword.setText("Password");

        TFLusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLusernameActionPerformed(evt);
            }
        });

        BAdd.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        BAdd.setText("Add");
        BAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });

        BReset.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        BReset.setText("Reset");
        BReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        LHeadingLogin.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        LHeadingLogin.setText("Add New Admin ");

        LPassword1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LPassword1.setText("Name");

        TFLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(LHeadingLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BReset)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BAdd))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(LPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(TFLname, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFLusername, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PFLpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LHeadingLogin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LUsername)
                    .addComponent(TFLusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PFLpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LPassword))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPassword1)
                    .addComponent(TFLname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BReset)
                    .addComponent(BAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PFLpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFLpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PFLpasswordKeyPressed

    private void TFLusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLusernameActionPerformed

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
        try {
            // TODO add your handling code here:
            String un = TFLusername.getText();                        //get username from user
            String ps = String.valueOf(PFLpassword.getPassword());
            String name = TFLname.getText();
            /*
            String selectQuery="select * from user_details where userid='"+un+"'";
            rs = pst.executeQuery(selectQuery);
            if(rs.next()) {
                InfoMessage("Account already registered.", "Registration Failed");
                TFRweburl.setText(null);
                TFRlname.setText(null);
                TFRfname.setText(null);
                PFRpassword.setText(null);
                TFRemail.setText(null);
                TFRusername.setText(null);
            }
            else { */
            String sel = "insert into admin_details values(?, ?, ?)";
            con = DriverManager.getConnection(URL, USER, PASS);
            pst = con.prepareStatement(sel);
            pst.setString(1, un);
            pst.setString(2, name);
            pst.setString(3, ps);
            pst.executeUpdate();
            InfoMessage("New Admin Added", "Admin List Updated");
            TFLusername.setText(null);
            PFLpassword.setText(null);
            TFLname.setText(null);
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BAddActionPerformed

    public void InfoMessage(String message, String tittle) {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        TFLusername.setText(null);
        PFLpassword.setText(null);
        TFLname.setText(null);
    }//GEN-LAST:event_BResetActionPerformed

    private void TFLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLnameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BReset;
    private javax.swing.JLabel LHeadingLogin;
    private javax.swing.JLabel LPassword;
    private javax.swing.JLabel LPassword1;
    private javax.swing.JLabel LUsername;
    private javax.swing.JPasswordField PFLpassword;
    private javax.swing.JTextField TFLname;
    private javax.swing.JTextField TFLusername;
    // End of variables declaration//GEN-END:variables
}
