/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.reservation.system;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sijo
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }
    private static final String URL = "jdbc:h2:~/BR";
    private static final String USER = "root";
    private static final String PASS = "";

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    ResultSetMetaData rsmd = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LHeadingLogin = new javax.swing.JLabel();
        LUsername = new javax.swing.JLabel();
        LPassword = new javax.swing.JLabel();
        TFLusername = new javax.swing.JTextField();
        BLoginto = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        PFLpassword = new javax.swing.JPasswordField();
        BBackLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LHeadingLogin.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        LHeadingLogin.setText("Bus Reservation Admin Login");

        LUsername.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LUsername.setText("Username");

        LPassword.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LPassword.setText("Password");

        TFLusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLusernameActionPerformed(evt);
            }
        });

        BLoginto.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        BLoginto.setText("Login");
        BLoginto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BLoginto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogintoActionPerformed(evt);
            }
        });

        BReset.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        BReset.setText("Reset");
        BReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        PFLpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PFLpasswordKeyPressed(evt);
            }
        });

        BBackLogin.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        BBackLogin.setText("<-");
        BBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBackLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BBackLogin))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BLoginto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFLusername, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PFLpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LHeadingLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BBackLogin)
                .addGap(74, 74, 74)
                .addComponent(LHeadingLogin)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFLusername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPassword)
                    .addComponent(PFLpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BReset)
                    .addComponent(BLoginto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void InfoMessage(String message, String tittle) {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }

    private void TFLusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLusernameActionPerformed

    private void BLogintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogintoActionPerformed
        try {
            int k = 0;
            con = DriverManager.getConnection(URL, USER, PASS);
            String sel = "select username, password from admin_details";
            pst = con.prepareStatement(sel);
            rs = pst.executeQuery();
            String un = TFLusername.getText();                        //get username from user
            String ps = String.valueOf(PFLpassword.getPassword());
            while (rs.next()) {
                if (un.equals(rs.getString(1)) & ps.equals(rs.getString(2))) {
                    InfoMessage("You have succesfully logged in!", "Login Succesfull");
                    dispose();
                    AdminControlPanel mp = new AdminControlPanel(un);
                    mp.setLocationRelativeTo(null);
                    mp.setVisible(true);
                    TFLusername.setText(null);
                    PFLpassword.setText(null);
                    k = 1;
                }
            }
            if (k == 0) {
                InfoMessage("Username/Password is Incorrect", "Login Error");
                TFLusername.setText(null);
                PFLpassword.setText(null);
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BLogintoActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        TFLusername.setText(null);
        PFLpassword.setText(null);
    }//GEN-LAST:event_BResetActionPerformed

    private void BBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBackLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        MainScreen mr = new MainScreen();
        mr.setLocationRelativeTo(null);
        mr.setVisible(true);
    }//GEN-LAST:event_BBackLoginActionPerformed

    private void PFLpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFLpasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //enterpress();
        }

    }//GEN-LAST:event_PFLpasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBackLogin;
    private javax.swing.JButton BLoginto;
    private javax.swing.JButton BReset;
    private javax.swing.JLabel LHeadingLogin;
    private javax.swing.JLabel LPassword;
    private javax.swing.JLabel LUsername;
    private javax.swing.JPasswordField PFLpassword;
    private javax.swing.JTextField TFLusername;
    // End of variables declaration//GEN-END:variables

    /*private void enterpress() {
        String un = TFLusername.getText();                        //get username from user
        String ps = String.valueOf(PFLpassword.getPassword());
        if (un.equals("admin") & ps.equals("pass")) {
            dispose();
            AdminControlPanel ap = new AdminControlPanel();
            ap.setLocationRelativeTo(null);
            ap.setVisible(true);
        }
    }*/
}
