/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.reservation.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sijo
 */
public class EditAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditAdmin
     */
    private static final String URL = "jdbc:h2:~/BR";
    private static final String USER = "root";
    private static final String PASS = "";

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    ResultSetMetaData rsmd = null;
    String adminuser;

    public EditAdmin() {
        initComponents();
    }

    EditAdmin(String auser) {
        initComponents();
        this.adminuser = auser;
        TFLusername.setText(auser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PFLoldpassword = new javax.swing.JPasswordField();
        LUsername = new javax.swing.JLabel();
        LPassword = new javax.swing.JLabel();
        TFLusername = new javax.swing.JTextField();
        BSave = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        LHeadingLogin = new javax.swing.JLabel();
        LPassword1 = new javax.swing.JLabel();
        PFLnewpassword = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        PFLoldpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PFLoldpasswordKeyPressed(evt);
            }
        });

        LUsername.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LUsername.setText("Username");

        LPassword.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LPassword.setText("Old Password");

        TFLusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLusernameActionPerformed(evt);
            }
        });

        BSave.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        BSave.setText("Save");
        BSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSaveActionPerformed(evt);
            }
        });

        BReset.setFont(new java.awt.Font("Verdana", 1, 19)); // NOI18N
        BReset.setText("Reset");
        BReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        LHeadingLogin.setFont(new java.awt.Font("URW Bookman L", 1, 24)); // NOI18N
        LHeadingLogin.setText("Edit Admin Details");

        LPassword1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LPassword1.setText("New Password");

        PFLnewpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PFLnewpasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LHeadingLogin)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PFLnewpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BSave))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFLusername, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PFLoldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LPassword1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LHeadingLogin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFLusername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PFLoldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PFLnewpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LPassword1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BReset)
                    .addComponent(BSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PFLoldpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFLoldpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PFLoldpasswordKeyPressed

    private void TFLusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFLusernameActionPerformed

    private void BSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSaveActionPerformed
        try {
            String un = TFLusername.getText();                        //get username from user
            String ops = String.valueOf(PFLoldpassword.getPassword());
            String nps = String.valueOf(PFLnewpassword.getPassword());
            String s = "update admin_details set username='" + un + "',password='" + nps + "' where password='" + ops + "' and username='" + un + "'";
            con = DriverManager.getConnection(URL, USER, PASS);
            pst = con.prepareStatement(s);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Details Updated");
            TFLusername.setText(null);
            PFLoldpassword.setText(null);
            PFLnewpassword.setText(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_BSaveActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        TFLusername.setText(null);
        PFLoldpassword.setText(null);
    }//GEN-LAST:event_BResetActionPerformed

    private void PFLnewpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFLnewpasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PFLnewpasswordKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BReset;
    private javax.swing.JButton BSave;
    private javax.swing.JLabel LHeadingLogin;
    private javax.swing.JLabel LPassword;
    private javax.swing.JLabel LPassword1;
    private javax.swing.JLabel LUsername;
    private javax.swing.JPasswordField PFLnewpassword;
    private javax.swing.JPasswordField PFLoldpassword;
    private javax.swing.JTextField TFLusername;
    // End of variables declaration//GEN-END:variables
}
