/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.reservation.system;

import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sijo
 */
public class NewBooking extends javax.swing.JInternalFrame {

    int index;
    /**
     * Creates new form NewBooking
     */
    private static final String URL = "jdbc:h2:~/BR";
    private static final String USER = "root";
    private static final String PASS = "";

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    ResultSetMetaData rsmd = null;

    public NewBooking(String u) {
        initComponents();
        jLabel2.setText(u);
        try {
            String sel = "select * from bus_booking where User='" + jLabel2.getText() + "'";
            con = DriverManager.getConnection(URL, USER, PASS);
            pst = con.prepareStatement(sel);
            rs = pst.executeQuery();
            while (rs.next()) {
                String user = rs.getString(1);
                String bno = rs.getString(2);
                String paid = rs.getString(3);
                String seats = rs.getString(4);
                String name = rs.getString(5);
                DefaultTableModel model2 = (DefaultTableModel) jTable6.getModel();
                model2.addRow(
                        new Object[]{
                            user, bno, paid, seats, name
                        }
                );
            }
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Search Result ....");

        jTable6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Bus No.", "Paid", "Seats", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Your Booking ...");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus No.", "Source", "Destination", "Time", "Price", "Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 27)); // NOI18N
        jLabel6.setText("Add Booking ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Source");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        cb1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KLM", "EKM", "TVM", "KNR", "VAK" }));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Destination");

        cb2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KLM", "EKM", "TVM", "KNR", "VAK" }));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(19, 19, 19)
                                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        index = jTable5.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        String bus_no = (String) model.getValueAt(index, 0);
        String source = (String) model.getValueAt(index, 1);
        String dest = (String) model.getValueAt(index, 2);
        String time = (String) model.getValueAt(index, 3);
        String price = (String) model.getValueAt(index, 4);
        String avail_seat = (String) model.getValueAt(index, 5);

        BookingFormFrame = new JFrame();
        BookingFormPanel = new JPanel();
        gl = new GridLayout(0, 4);
        l1 = new JLabel("Bus No");
        l11 = new JLabel(bus_no);
        l3 = new JLabel("Source");
        l13 = new JLabel(source);
        l4 = new JLabel("Dest");
        l14 = new JLabel(dest);
        l6 = new JLabel("Time");
        l16 = new JLabel(time);
        l7 = new JLabel("Price");
        l17 = new JLabel(String.valueOf(price));
        l8 = new JLabel("Available Seat");
        l18 = new JLabel(String.valueOf(avail_seat));
        seatnoL = new JLabel("Seats");
        idnoL = new JLabel("ID No.");
        fnameL = new JLabel("First Name");
        lnameL = new JLabel("Last Name");
        t1 = new JTextField(20);
        t3 = new JTextField(20);

        BookingFormFrame.getContentPane().add(BookingFormPanel);
        BookingFormPanel.setLayout(gl);

        BookingFormPanel.add(l1);
        BookingFormPanel.add(l11);
        BookingFormPanel.add(l3);
        BookingFormPanel.add(l13);
        BookingFormPanel.add(l4);
        BookingFormPanel.add(l14);
        BookingFormPanel.add(l6);
        BookingFormPanel.add(l16);
        BookingFormPanel.add(l7);
        BookingFormPanel.add(l17);
        BookingFormPanel.add(l8);
        BookingFormPanel.add(l18);

        BookingFormPanel.add(seatnoL);
        BookingFormPanel.add(t1);
        BookingFormPanel.add(fnameL);
        BookingFormPanel.add(t3);
        int result = JOptionPane.showConfirmDialog(BookingFormFrame, BookingFormPanel, "Booking Form", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            //JOptionPane.showMessageDialog(this, "entered in ok");
            String booking_user = jLabel2.getText();
            String seatno = t1.getText();
            String first_tname = t3.getText();
            int remaining_seat = Integer.parseInt(avail_seat) - Integer.parseInt(seatno);
            int price_paid = Integer.parseInt(seatno) * Integer.parseInt(price);
            try {
                /* String sel = "select * from bus_booking where bus_no ='"+bus_no+"' and User='"+booking_user+"'";
            con = DriverManager.getConnection(URL, USER, PASS);
            pst = con.prepareStatement(sel);
            rs = pst.executeQuery(); */
                //JOptionPane.showMessageDialog(this, "entered in try");
                String si;
                try {
                    si = "insert into bus_booking values('" + booking_user + "','" + bus_no + "','" + price_paid + "','" + seatno + "','" + first_tname + "')";
                    con = DriverManager.getConnection(URL, USER, PASS);
                    pst = con.prepareStatement(si);
                    pst.execute();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
                //JOptionPane.showMessageDialog(this, "insertion completed");
                try {
                    String updateQuery = "update bus_details set total_seat='" + remaining_seat + "' where bus_no='" + bus_no + "'";
                    con = DriverManager.getConnection(URL, USER, PASS);
                    pst = con.prepareStatement(updateQuery);
                    pst.execute();
                    //JOptionPane.showMessageDialog(this, "bus details updated");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
                int aa = JOptionPane.showConfirmDialog(null, "Booking Done", "Sure !!!", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (aa == JOptionPane.OK_OPTION) {

                    DefaultTableModel model0 = (DefaultTableModel) jTable6.getModel();
                    int x = model0.getRowCount();
                    int k;
                    if (x != 0) {
                        for (k = 0; k < x; k++) {
                            model0.removeRow(0);
                        }
                    }
                    DefaultTableModel model9 = (DefaultTableModel) jTable5.getModel();
                    int y = model9.getRowCount();
                    int p;
                    if (y != 0) {
                        for (p = 0; p < y; p++) {
                            model9.removeRow(0);
                        }
                    }
                    try {
                        String ss = "select * from bus_booking where User='" + jLabel2.getText() + "'";
                        con = DriverManager.getConnection(URL, USER, PASS);
                        pst = con.prepareStatement(ss);
                        rs = pst.executeQuery();
                        DefaultTableModel model2 = (DefaultTableModel) jTable6.getModel();
                        while (rs.next()) {
                            model2.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
                        }
                        // JOptionPane.showMessageDialog(this, "Displayed on right side");
                        con.close();

                        String sel = "select * from bus_details where bus_source='" + cb1.getSelectedItem() + "' and bus_dest='" + cb2.getSelectedItem() + "'";
                        con = DriverManager.getConnection(URL, USER, PASS);
                        pst = con.prepareStatement(sel);
                        rs = pst.executeQuery();
                        DefaultTableModel model3 = (DefaultTableModel) jTable5.getModel();
                        while (rs.next()) {
                            model3.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
                        }
                        // JOptionPane.showMessageDialog(this, "Displayed on left side");
                        con.close();
                    } catch (SQLException e) {
                        System.out.println(e);
                    }

                }
                con.close();
            } catch (HeadlessException | SQLException e) {
                System.out.println(e);
            }
        }

    }//GEN-LAST:event_jTable5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultTableModel model0 = (DefaultTableModel) jTable6.getModel();
        int x = model0.getRowCount();
        if (x != 0) {
            for (int i = 0; i < x; i++) {
                model0.removeRow(0);
            }
        }
        try {
            String sel = "select * from bus_details where bus_source='" + cb1.getSelectedItem() + "' and bus_dest='" + cb2.getSelectedItem() + "'";
            con = DriverManager.getConnection(URL, USER, PASS);
            pst = con.prepareStatement(sel);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
        try {
            String sel = "select * from bus_booking where User='" + jLabel2.getText() + "'";
            con = DriverManager.getConnection(URL, USER, PASS);
            pst = con.prepareStatement(sel);
            rs = pst.executeQuery();
            while (rs.next()) {
                String user = rs.getString(1);
                String bno = rs.getString(2);
                String paid = rs.getString(3);
                String seats = rs.getString(4);
                String name = rs.getString(5);
                DefaultTableModel model2 = (DefaultTableModel) jTable6.getModel();
                model2.addRow(
                        new Object[]{
                            user, bno, paid, seats, name
                        }
                );
            }
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model0 = (DefaultTableModel) jTable6.getModel();
        int x = model0.getRowCount();
        if (x != 0) {
            for (int i = 0; i < x; i++) {
                model0.removeRow(0);
            }
        }
        try {
            String sel = "select * from bus_details where bus_source='" + cb1.getSelectedItem() + "' and bus_dest='" + cb2.getSelectedItem() + "'";
            con = DriverManager.getConnection(URL, USER, PASS);
            pst = con.prepareStatement(sel);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    GridLayout gl;
    public JFrame BookingFormFrame;
    public JPanel BookingFormPanel;
    public JLabel l1, l3, l4, l6, l7, l8, l11, l13, l14, l16, l17, l18, seatnoL, idnoL, fnameL, lnameL;
    public JComboBox seatCB;
    public JTextField t1, t3;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    // End of variables declaration//GEN-END:variables
}
