/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.reservation.system;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sijo
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }
    private static final String URL = "jdbc:h2:~/BR";
    private static final String USER = "root";
    private static final String PASS = "";

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    ResultSetMetaData rsmd = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LHeadingRegistration = new javax.swing.JLabel();
        LRusername = new javax.swing.JLabel();
        LRemail = new javax.swing.JLabel();
        LRpassword = new javax.swing.JLabel();
        LRcpassword = new javax.swing.JLabel();
        TFRusername = new javax.swing.JTextField();
        TFRemail = new javax.swing.JTextField();
        PFRpassword = new javax.swing.JPasswordField();
        BRegister = new javax.swing.JButton();
        BRRest = new javax.swing.JButton();
        RLabel1 = new javax.swing.JLabel();
        LSignIn = new javax.swing.JLabel();
        TFRfname = new javax.swing.JTextField();
        LRcpassword1 = new javax.swing.JLabel();
        TFRlname = new javax.swing.JTextField();
        LRcpassword2 = new javax.swing.JLabel();
        TFRweburl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LHeadingRegistration.setFont(new java.awt.Font("URW Gothic L", 1, 28)); // NOI18N
        LHeadingRegistration.setText("User Registration");

        LRusername.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        LRusername.setText("Username");

        LRemail.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        LRemail.setText("Email");

        LRpassword.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        LRpassword.setText("Password");

        LRcpassword.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        LRcpassword.setText("First Name");

        BRegister.setText("Register");
        BRegister.setToolTipText("");
        BRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegisterActionPerformed(evt);
            }
        });

        BRRest.setText("Reset");
        BRRest.setToolTipText("");
        BRRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRRestActionPerformed(evt);
            }
        });

        RLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        RLabel1.setText("Already have an account?");

        LSignIn.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        LSignIn.setText("Sign In!");
        LSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LSignInMouseClicked(evt);
            }
        });

        LRcpassword1.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        LRcpassword1.setText("Last Name");

        LRcpassword2.setFont(new java.awt.Font("Umpush", 0, 15)); // NOI18N
        LRcpassword2.setText("Web URL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LRusername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TFRusername, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LRemail)
                            .addComponent(LRcpassword)
                            .addComponent(LRpassword)
                            .addComponent(LRcpassword1)
                            .addComponent(LRcpassword2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TFRemail, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(PFRpassword))
                            .addComponent(TFRfname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFRlname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFRweburl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BRRest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LSignIn)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(LHeadingRegistration)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LHeadingRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRusername)
                    .addComponent(TFRusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRemail)
                    .addComponent(TFRemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRpassword)
                    .addComponent(PFRpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRcpassword)
                    .addComponent(TFRfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFRlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LRcpassword1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRcpassword2)
                    .addComponent(TFRweburl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BRRest)
                    .addComponent(BRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RLabel1)
                    .addComponent(LSignIn))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSignInMouseClicked
        // TODO add your handling code here:
        dispose();
        UserLogin ul = new UserLogin();
        ul.setLocationRelativeTo(null);
        ul.setVisible(true);
    }//GEN-LAST:event_LSignInMouseClicked

    private void BRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegisterActionPerformed
        try {
            // TODO add your handling code here:
            String un = TFRusername.getText();                        //get username from user
            String ps = String.valueOf(PFRpassword.getPassword());
            String em = TFRemail.getText();
            String fn = TFRfname.getText();
            String ln = TFRlname.getText();
            String wu = TFRweburl.getText();
            /*
            String selectQuery="select * from user_details where userid='"+un+"'";
            rs = pst.executeQuery(selectQuery);
            if(rs.next()) {
                InfoMessage("Account already registered.", "Registration Failed");
                TFRweburl.setText(null);
                TFRlname.setText(null);
                TFRfname.setText(null);
                PFRpassword.setText(null);
                TFRemail.setText(null);
                TFRusername.setText(null);
            }
            else { */
            String sel = "insert into user_details values(?, ?, ?, ?, ?, ?)";
            con = DriverManager.getConnection(URL, USER, PASS);
            pst = con.prepareStatement(sel);
            pst.setString(1, un);
            pst.setString(2, fn);
            pst.setString(3, ln);
            pst.setString(4, ps);
            pst.setString(5, em);
            pst.setString(6, wu);
            pst.executeUpdate();
            InfoMessage("Your account has been created!", "Registration Succesful");
            dispose();
            UserLogin ul = new UserLogin();
            ul.setLocationRelativeTo(null);
            ul.setVisible(true);
            TFRweburl.setText(null);
            TFRlname.setText(null);
            TFRfname.setText(null);
            PFRpassword.setText(null);
            TFRemail.setText(null);
            TFRusername.setText(null);
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BRegisterActionPerformed

    private void BRRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRRestActionPerformed
        // TODO add your handling code here:
        TFRweburl.setText(null);
        TFRlname.setText(null);
        TFRfname.setText(null);
        PFRpassword.setText(null);
        TFRemail.setText(null);
        TFRusername.setText(null);
    }//GEN-LAST:event_BRRestActionPerformed
    public void InfoMessage(String message, String tittle) {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRRest;
    private javax.swing.JButton BRegister;
    private javax.swing.JLabel LHeadingRegistration;
    private javax.swing.JLabel LRcpassword;
    private javax.swing.JLabel LRcpassword1;
    private javax.swing.JLabel LRcpassword2;
    private javax.swing.JLabel LRemail;
    private javax.swing.JLabel LRpassword;
    private javax.swing.JLabel LRusername;
    private javax.swing.JLabel LSignIn;
    private javax.swing.JPasswordField PFRpassword;
    private javax.swing.JLabel RLabel1;
    private javax.swing.JTextField TFRemail;
    private javax.swing.JTextField TFRfname;
    private javax.swing.JTextField TFRlname;
    private javax.swing.JTextField TFRusername;
    private javax.swing.JTextField TFRweburl;
    // End of variables declaration//GEN-END:variables

    private void print(String the_Passwords_do_not_match) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
